[build]
builder = "dockerfile"
dockerfilePath = "infrastructure/docker/Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
PORT = { default = "8000" }
ENVIRONMENT = { default = "production" }
QDRANT_URL = { required = true }
QDRANT_API_KEY = { required = true }

[build.env]
PYTHON_VERSION = "3.11"